### ISSUE TITLE
这里可能有坑

### ISSUE THREAD

**Issue by huangdijia** [hyperf/biz-skeleton#14]
https://github.com/hyperf/biz-skeleton/blob/3aa596444bd31058b08fd252742690dfee620779/config/autoload/dependencies.php#L13

复现条件：

- 日志 handler 使用：`Monolog\Handler\SyslogUdpHandler::class`
- 监听 BootApplication 事件：里面执行 `$this->logger->xxx()`

会报：

```shell
swoole_socket_sendto(): Argument #1 ($socket) must be of type Swoole\Coroutine\Socket, Socket given
PHP Fatal error:  Uncaught TypeError: swoole_socket_sendto(): Argument #1 ($socket) must be of type Swoole\Coroutine\Socket, Socket given in @swoole-src/library/ext/sockets.php:62
Stack trace:
#0 [internal function]: swoole_socket_sendto()
#1 /mnt/c/dev/user-center/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdp/UdpSocket.php(79): socket_sendto()
#2 /mnt/c/dev/user-center/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdp/UdpSocket.php(41): Monolog\Handler\SyslogUdp\UdpSocket->send()
#3 /mnt/c/dev/user-center/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdpHandler.php(77): Monolog\Handler\SyslogUdp\UdpSocket->write()
#4 /mnt/c/dev/user-center/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): 
Monolog\Handler\SyslogUdpHandler->write()
#5 /mnt/c/dev/user-center/vendor/monolog/monolog/src/Monolog/Logger.php(359): Monolog\Handler\AbstractProcessingHandler->handle()
#6 /mnt/c/dev/user-center/vendor/monolog/monolog/src/Monolog/Logger.php(602): Monolog\Logger->addRecord()
#7 /mnt/c/dev/user-center/vendor/hyperf/command/src/Listener/FailToHandleListener.php(38): Monolog\Logger->error()
#8 /mnt/c/dev/user-center/vendor/hyperf/event/src/EventDispatcher.php(36): Hyperf\Command\Listener\FailToHandleListener->process()
#9 /mnt/c/dev/user-center/vendor/hyperf/command/src/Command.php(435): Hyperf\Event\EventDispatcher->dispatch()
#10 [internal function]: Hyperf\Command\Command->Hyperf\Command\{closure}()
#11 {main}
  thrown in @swoole-src/library/ext/sockets.php on line 62
```

原因分析：非协程环境实例了 socket 对象，在协程环境下使用导致的。

**Comment by limingxinleo** [comment]
这里自己注意下吧。。。

**Comment by huangdijia** [comment]
嗯额
